from react_work import models
from reportlab.platypus import SimpleDocTemplate, Table as RLTable, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table as XLTable, TableStyleInfo
from io import BytesIO, StringIO
import base64
import csv
from datetime import datetime
from decimal import Decimal
import json


class PDF():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Inventory Items Report for {self.location}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Item Name', 'Brand', 'Quantity', 'Cost', 'Price', 'Total Value']
        table_data = [headers]

        total_quantity = 0
        total_value = Decimal('0.0')

        for item in self.data:
            qty = item.get('quantity', 0) or 0
            cost = Decimal(str(item.get('purchase_price', 0.0) or 0.0))
            price = item.get('sales_price', 0.0) or 0.0
            row_total = Decimal(qty) * cost

            total_quantity += qty
            total_value += row_total

            row = [
                item.get('code', ''),
                item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''),
                item.get('brand__name', ''),
                str(int(qty)),
                f"{cost:.2f}",
                f"{price:.2f}",
                f"{row_total:.2f}",
            ]
            table_data.append(row)

        totals_row = [
            '',
            'TOTALS',
            '',
            str(total_quantity),
            '',
            '',
            f"{total_value:.2f}",
        ]
        table_data.append(totals_row)

        col_widths = [60, 170, 100, 50, 60, 60, 70]

        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),

            ('FONTNAME', (1, -1), (1, -1), 'Helvetica-Bold'),
            ('TEXTCOLOR', (1, -1), (1, -1), colors.black),
            ('SPAN', (0, -1), (0, -1)),
        ])
        rl_table.setStyle(rl_style)

        flowables.append(rl_table)
        doc.build(flowables)

        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_transfer_main_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))
        
        headers = ['Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']

        table_data = [headers]
        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('from_loc__location_name', ''),
                item.get('to_loc__location_name', ''),
                str(int(item.get('total_quantity', 0) or 0)),
                item.get('status', ''),
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('total_quantity', 0) or 0) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            str(total_quantity),
            '',
        ]
        table_data.append(totals_row)

        col_widths = [82, 68, 150, 90, 90, 50, 70]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (2, 1), (2, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])
        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_transfer_detail_pdf(self, details):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Transfer Detail for {details.get('number')}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Posted by: {details.get('by')} on {details.get('issueDate')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        info_table = RLTable(info_data, colWidths=[80, 400])
        info_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])
        info_table.setStyle(info_style)
        flowables.append(info_table)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        table_data = [headers]

        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('name', ''),
                item.get('brand', ''),
                item.get('category', ''),
                item.get('model', ''),
                str(int(item.get('qty', 0) or 0)),
                item.get('unit', ''),
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            str(total_quantity),
            '',
        ]
        table_data.append(totals_row)

        col_widths = [70, 150, 100, 100, 80, 50, 50]

        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])
        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_sales_main_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Sales Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        headers = ['Sales ID', 'Date', 'Description', 'Customer', 'Location', 'Total Amount', 'Status']

        table_data = [headers]
        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('customer_name', '') if item.get('customer_info__name') == 'Regular Customer' else item.get('customer_info__name', ''),
                item.get('location_address__location_name', ''),
                f"{item.get('gross_total', 0.0):.2f}",
                item.get('status', ''),
            ]
            table_data.append(row)

        total_amount = sum(Decimal(str(item.get('gross_total', 0.0) or 0.0)) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            f"{total_amount:.2f}",
            '',
        ]
        table_data.append(totals_row)

        col_widths = [82, 68, 130, 80, 80, 80, 70]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (2, 1), (2, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])
        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'sales_report_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_sales_detail_pdf(self, details):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Sales Detail for {details.get('number')}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Posted by: {details.get('by')} on {details.get('issueDate')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        info_data = [
            ['Customer:', details['customer'] if details['customer'].strip() else details['customer_info']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        info_table = RLTable(info_data, colWidths=[80, 400])
        info_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])
        info_table.setStyle(info_style)
        flowables.append(info_table)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Brand', 'Item Name', 'Quantity', 'Unit Price', 'Total Price']

        table_data = [headers]
        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('brand', ''),
                item.get('item', ''),
                str(int(item.get('qty', 0) or 0)),
                f"{Decimal(str(item.get('price', 0.0) or 0.0)):.2f}",
                f"{Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)):.2f}",
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        total_price = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        totals_row = [
            '',
            '',
            'TOTALS',
            str(total_quantity),
            '',
            f"{total_price:.2f}",
        ]

        table_data.append(totals_row)
        col_widths = [60, 80, 180, 60, 80, 80]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])

        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        gross_amount = total_price
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        discount_tax = [
            ['Gross Total :', f"{Decimal(str(gross_amount)):.2f}"],
            [f'Discount - {discount}% :', f"- {discount_amount:.2f}"],
        ]
        for levy in tax_levy_list:
            discount_tax.append([f"{levy['name']} :", f"+ {levy['amount']:.2f}"])
        discount_tax.append(['Net Total :', f"{net_amount:.2f}"])

        discount_tax_table = RLTable(discount_tax, colWidths=[100, 80], hAlign='RIGHT')
        discount_tax_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])

        discount_tax_table.setStyle(discount_tax_style)
        flowables.append(Spacer(1, 12))
        flowables.append(discount_tax_table)


        doc.build(flowables)
        buffer.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'sales_detail_{details.get('number')}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_purchase_main_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Purchase Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        headers = ['Purchase ID', 'Date', 'Description', 'Supplier', 'Location', 'Total Amount', 'Status']

        table_data = [headers]
        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('supplier__name', ''),
                item.get('location_address__location_name', ''),
                f"{item.get('gross_total', 0.0):.2f}",
                item.get('status', ''),
            ]
            table_data.append(row)

        total_amount = sum(Decimal(str(item.get('gross_total', 0.0) or 0.0)) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            f"{total_amount:.2f}",
            '',
        ]
        table_data.append(totals_row)

        col_widths = [82, 68, 130, 80, 80, 80, 70]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (2, 1), (2, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])

        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'purchase_report_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_purchase_detail_pdf(self, details):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Purchase Detail for {details.get('number')}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Posted by: {details.get('by')} on {details.get('issueDate')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        info_data = [
            ['Supplier:', details['supplier']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        info_table = RLTable(info_data, colWidths=[80, 400])
        info_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])
        info_table.setStyle(info_style)
        flowables.append(info_table)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Brand', 'Item Name', 'Quantity', 'Unit Cost', 'Total Price']
        table_data = [headers]

        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('brand', ''),
                item.get('item', ''),
                str(int(item.get('qty', 0) or 0)),
                f"{Decimal(str(item.get('price', 0.0) or 0.0)):.2f}",
                f"{Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)):.2f}",
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        total_price = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        totals_row = [
            '',
            '',
            'TOTALS',
            str(total_quantity),
            '',
            f"{total_price:.2f}",
        ]
        table_data.append(totals_row)

        col_widths = [60, 80, 180, 60, 80, 80]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])

        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        gross_amount = total_price
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        discount_tax = [
            ['Gross Total :', f"{Decimal(str(gross_amount)):.2f}"],
            [f'Discount - {discount}% :', f"- {discount_amount:.2f}"],
        ]

        for levy in tax_levy_list:
            discount_tax.append([f"{levy['name']} :", f"+ {levy['amount']:.2f}"])

        discount_tax.append(['Net Total :', f"{net_amount:.2f}"])

        discount_tax_table = RLTable(discount_tax, colWidths=[100, 80], hAlign='RIGHT')
        discount_tax_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])

        discount_tax_table.setStyle(discount_tax_style)
        flowables.append(Spacer(1, 12))
        flowables.append(discount_tax_table)

        doc.build(flowables)
        buffer.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'purchase_detail_{details.get('number')}_{today}.pdf',
            'type': 'application/pdf'
        }



class XLSX():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Inventory Items")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Inventory Items Report for {self.location}"
        ws.merge_cells('A1:K1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:K2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Item Code', 'Item Name', 'Category', 'Brand', 'Model', 'Quantity', 'Unit', 'Cost', 'Price', 'Total Value']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        total_quantity = 0
        total_value = Decimal('0.0')

        for row_index, item in enumerate(self.data, start=5):
            qty = int(item.get('quantity', 0) or 0)
            cost_raw = item.get('purchase_price', 0.0) or 0.0

            cost = Decimal(str(cost_raw))
            row_total = Decimal(qty) * cost

            total_quantity += int(qty)
            total_value += row_total

            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''))
            ws.cell(row=row_index, column=4, value=item.get('category__name', ''))
            ws.cell(row=row_index, column=5, value=item.get('brand__name', ''))
            ws.cell(row=row_index, column=6, value=item.get('model', ''))
            ws.cell(row=row_index, column=7, value=int(qty))
            ws.cell(row=row_index, column=8, value=item.get('unit__suffix', ''))

            ws.cell(row=row_index, column=9, value=float(cost))
            ws.cell(row=row_index, column=10, value=float(item.get('sales_price', 0.0)))
            ws.cell(row=row_index, column=11, value=float(row_total))

        last_data_row = 4 + len(self.data)
        totals_row = last_data_row + 1
        ws.cell(row=totals_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=totals_row, column=7, value=total_quantity).font = Font(bold=True)
        ws.cell(row=totals_row, column=11, value=total_value).font = Font(bold=True)

        last_row = max(4, last_data_row + 1)
        ref = f"B4:K{last_row}"
        table = XLTable(displayName="ItemsTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)

        ws.sheet_view.showGridLines = False

        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_transfer_main_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Transfer Report")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"
        ws.merge_cells('A1:H1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:H2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=5):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '')
            ws.cell(row=row_index, column=4, value=item.get('description', ''))
            ws.cell(row=row_index, column=5, value=item.get('from_loc__location_name', ''))
            ws.cell(row=row_index, column=6, value=item.get('to_loc__location_name', ''))
            ws.cell(row=row_index, column=7, value=int(item.get('total_quantity', 0) or 0))
            ws.cell(row=row_index, column=8, value=item.get('status', ''))

        last_row = 4 + len(self.data)

        total_row = last_row + 1
        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G5:G{last_row})").font = Font(bold=True)
        

        last_row = max(4, last_row + 1)
        ref = f"B4:H{last_row}"
        table = XLTable(displayName="TransferTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_transfer_detail_xlsx(self, details):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Transfer Detail")
        ws.freeze_panes = 'A10'

        header_font = Font(bold=True)

        ws['A1'] = f"Transfer Detail for {details.get('number')}"
        ws.merge_cells('A1:G1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Posted by: {details.get('by')} on {details.get('issueDate')}"
        ws.merge_cells('A2:G2')
        ws['A2'].alignment = Alignment(horizontal='center')

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']]
        ]
        for row_offset, (label, value) in enumerate(info_data, start=4):
            ws.cell(row=row_offset, column=2, value=label).font = Font(bold=True)
            ws.cell(row=row_offset, column=3, value=value)

        headers = ['', 'Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=9, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=10):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('name', ''))
            ws.cell(row=row_index, column=4, value=item.get('brand', ''))
            ws.cell(row=row_index, column=5, value=item.get('category', ''))
            ws.cell(row=row_index, column=6, value=item.get('model', ''))
            ws.cell(row=row_index, column=7, value=int(item.get('qty', 0) or 0))
            ws.cell(row=row_index, column=8, value=item.get('unit', ''))

        last_row = 9 + len(self.data)
        total_row = last_row + 1
        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G7:G{last_row})").font = Font(bold=True)

        last_row = max(8, last_row + 1)
        ref = f"B9:H{last_row}"
        table = XLTable(displayName="TransferDetailTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_sales_main_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Sales Report")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Sales Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"
        ws.merge_cells('A1:K1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:K2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Sales ID', 'Date', 'Description', 'Customer', 'Location', 'Gross Amount', 'Discount', 'Tax Levy', 'Net Amount', 'Status']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=5):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '')
            ws.cell(row=row_index, column=4, value=item.get('description', ''))
            ws.cell(row=row_index, column=5, value=item.get('customer_name', '') if item.get('customer_info__name') == 'Regular Customer' else item.get('customer_info__name', ''))
            ws.cell(row=row_index, column=6, value=item.get('location_address__location_name', ''))
            ws.cell(row=row_index, column=7, value=float(item.get('sub_total', 0.0)))
            ws.cell(row=row_index, column=8, value=float(item.get('discount', 0.0)))
            ws.cell(row=row_index, column=9, value=float(item.get('tax_levy', 0.0)))
            ws.cell(row=row_index, column=10, value=float(item.get('gross_total', 0.0)))
            ws.cell(row=row_index, column=11, value=item.get('status', ''))

        last_row = 4 + len(self.data)

        total_row = last_row + 1
        ws.cell(row=total_row, column=6, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G5:G{last_row})").font = Font(bold=True)
        ws.cell(row=total_row, column=8, value=f"=SUM(H5:H{last_row})").font = Font(bold=True)
        ws.cell(row=total_row, column=9, value=f"=SUM(I5:I{last_row})").font = Font(bold=True)
        ws.cell(row=total_row, column=10, value=f"=SUM(J5:J{last_row})").font = Font(bold=True)

        last_row = max(4, last_row + 1)
        ref = f"B4:K{last_row}"
        table = XLTable(displayName="SalesTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()
        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'sales_report_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_sales_detail_xlsx(self, details):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Sales Detail")
        ws.freeze_panes = 'A10'

        header_font = Font(bold=True)

        ws['A1'] = f"Sales Detail for {details.get('number')}"
        ws.merge_cells('A1:L1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Posted by: {details.get('by')} on {details.get('issueDate')}"
        ws.merge_cells('A2:L2')
        ws['A2'].alignment = Alignment(horizontal='center')

        info_data = [
            ['Customer:', details['customer'] if details['customer'].strip() else details['customer_info']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']]
        ]
        for row_offset, (label, value) in enumerate(info_data, start=4):
            ws.cell(row=row_offset, column=2, value=label).font = Font(bold=True)
            ws.cell(row=row_offset, column=3, value=value)

        headers = ['', 'Item Code', 'Brand', 'Item Name', 'Quantity', 'Unit Price', 'Total Price']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=9, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=10):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('brand', ''))
            ws.cell(row=row_index, column=4, value=item.get('item', ''))
            ws.cell(row=row_index, column=5, value=int(item.get('qty', 0) or 0))
            ws.cell(row=row_index, column=6, value=float(Decimal(str(item.get('price', 0.0) or 0.0))))
            total_price = Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0))
            ws.cell(row=row_index, column=7, value=float(total_price))

        last_row = 9 + len(self.data)
        total_row = last_row + 1
        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=5, value=f"=SUM(E10:E{last_row})").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G10:G{last_row})").font = Font(bold=True)

        last_row = max(8, last_row + 1)
        ref = f"B9:G{last_row}"
        table = XLTable(displayName="SalesDetailTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style

        gross_amount = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        discount_tax_start_row = last_row + 3
        ws.cell(row=discount_tax_start_row, column=6, value="Gross Total :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row, column=7, value=float(gross_amount))
        ws.cell(row=discount_tax_start_row + 1, column=6, value=f"Discount - {discount}% :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row + 1, column=7, value=float(-discount_amount))

        for idx, levy in enumerate(tax_levy_list):
            ws.cell(row=discount_tax_start_row + 2 + idx, column=6, value=f"{levy['name']} :").font = Font(bold=True)
            ws.cell(row=discount_tax_start_row + 2 + idx, column=7, value=float(levy['amount']))

        ws.cell(row=discount_tax_start_row + 2 + len(tax_levy_list), column=6, value="Net Total :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row + 2 + len(tax_levy_list), column=7, value=float(net_amount))



        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'sales_detail_{details.get('number')}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_purchase_main_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Purchase Report")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Purchase Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"
        ws.merge_cells('A1:G1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:G2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Purchase ID', 'Date', 'Description', 'Supplier', 'Location', 'Total Amount', 'Status']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=5):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '')
            ws.cell(row=row_index, column=4, value=item.get('description', ''))
            ws.cell(row=row_index, column=5, value=item.get('supplier__name', ''))
            ws.cell(row=row_index, column=6, value=item.get('location_address__location_name', ''))
            ws.cell(row=row_index, column=7, value=float(item.get('gross_total', 0.0)))
            ws.cell(row=row_index, column=8, value=item.get('status', ''))

        last_row = 4 + len(self.data)

        total_row = last_row + 1
        ws.cell(row=total_row, column=6, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G5:G{last_row})").font = Font(bold=True)

        last_row = max(4, last_row + 1)
        ref = f"B4:H{last_row}"
        table = XLTable(displayName="PurchaseTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)

        ws.sheet_view.showGridLines = False

        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'purchase_report_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_purchase_detail_xlsx(self, details):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Purchase Detail")
        ws.freeze_panes = 'A10'

        header_font = Font(bold=True)

        ws['A1'] = f"Purchase Detail for {details.get('number')}"
        ws.merge_cells('A1:H1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Posted by: {details.get('by')} on {details.get('issueDate')}"
        ws.merge_cells('A2:H2')
        ws['A2'].alignment = Alignment(horizontal='center')

        info_data = [
            ['Supplier:', details['supplier']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']]
        ]
        for row_offset, (label, value) in enumerate(info_data, start=4):
            ws.cell(row=row_offset, column=2, value=label).font = Font(bold=True)
            ws.cell(row=row_offset, column=3, value=value)

        headers = ['', 'Item Code', 'Item Name', 'Brand', 'Quantity', 'Unit Price', 'Total Price']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=9, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=10):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('item', ''))
            ws.cell(row=row_index, column=4, value=item.get('brand', ''))
            ws.cell(row=row_index, column=5, value=int(item.get('qty', 0) or 0))
            ws.cell(row=row_index, column=6, value=float(Decimal(str(item.get('price', 0.0) or 0.0))))
            total_price = Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0))
            ws.cell(row=row_index, column=7, value=float(total_price))

        last_row = 9 + len(self.data)
        total_row = last_row + 1

        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=5, value=f"=SUM(E10:E{last_row})").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G10:G{last_row})").font = Font(bold=True)

        last_row = max(8, last_row + 1)
        ref = f"B9:G{last_row}"
        table = XLTable(displayName="PurchaseDetailTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style

        gross_amount = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        discount_tax_start_row = last_row + 3
        ws.cell(row=discount_tax_start_row, column=6, value="Gross Total :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row, column=7, value=float(gross_amount))
        ws.cell(row=discount_tax_start_row + 1, column=6, value=f"Discount - {discount}% :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row + 1, column=7, value=float(-discount_amount))

        for idx, levy in enumerate(tax_levy_list):
            ws.cell(row=discount_tax_start_row + 2 + idx, column=6, value=f"{levy['name']} :").font = Font(bold=True)
            ws.cell(row=discount_tax_start_row + 2 + idx, column=7, value=float(levy['amount']))

        ws.cell(row=discount_tax_start_row + 2 + len(tax_levy_list), column=6, value="Net Total :").font = Font(bold=True)
        ws.cell(row=discount_tax_start_row + 2 + len(tax_levy_list), column=7, value=float(net_amount))

        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'purchase_detail_{details.get('number')}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }


class CSV():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Inventory Items Report for {self.location}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Item Code', 'Item Name', 'Category', 'Brand', 'Model', 'Quantity', 'Unit', 'Cost', 'Price', 'Total Value']
        writer.writerow(headers)

        total_quantity = 0
        total_value = Decimal('0.0')

        for item in self.data:
            qty = item.get('quantity', 0) or 0
            cost = Decimal(str(item.get('purchase_price', 0.0) or 0.0))
            row_total = Decimal(qty) * cost

            total_quantity += int(qty)
            total_value += row_total

            writer.writerow([
                item.get('code', ''),
                item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''),
                item.get('category__name', ''),
                item.get('brand__name', ''),
                item.get('model', ''),
                int(qty),
                item.get('unit__suffix', ''),
                f"{cost:.2f}",
                f"{item.get('sales_price', 0.0):.2f}",
                f"{row_total:.2f}",
            ])

        writer.writerow(['', 'TOTALS', '', '', '', total_quantity, '', '', '', f"{total_value:.2f}"])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_transfer_main_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']
        writer.writerow(headers)

        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('from_loc__location_name', ''),
                item.get('to_loc__location_name', ''),
                int(item.get('total_quantity', 0) or 0),
                item.get('status', ''),
            ])

        writer.writerow(['', 'TOTALS', '', '', '', f"=SUM(F5:F{len(self.data)+1})", ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_transfer_detail_csv(self, details):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Transfer Detail for {details.get('number')}"]
        writer.writerow(info_row)
        generated_info = [f"Posted by: {details.get('by')} on {details.get('issueDate')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        for label, value in info_data:
            writer.writerow([label, value])
        writer.writerow([])

        headers = ['Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        writer.writerow(headers)

        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('name', ''),
                item.get('brand', ''),
                item.get('category', ''),
                item.get('model', ''),
                int(item.get('qty', 0) or 0),
                item.get('unit', ''),
            ])

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        writer.writerow(['', 'TOTALS', '', '', '', total_quantity, ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()
        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_sales_main_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Sales Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Sales ID', 'Date', 'Description', 'Customer', 'Location', 'Gross Amount', 'Discount', 'Tax Levy', 'Net Amount', 'Status']

        writer.writerow(headers)
        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('customer_name', '') if item.get('customer_info__name') == 'Regular Customer' else item.get('customer_info__name', ''),
                item.get('location_address__location_name', ''),
                f"{item.get('sub_total', 0.0):.2f}",
                f"{item.get('discount', 0.0):.2f}",
                f"{item.get('tax_levy', 0.0):.2f}",
                f"{item.get('gross_total', 0.0):.2f}",
                item.get('status', ''),
            ])

        total_gross = sum(Decimal(str(item.get('sub_total', 0.0) or 0.0)) for item in self.data)
        total_discount = sum(Decimal(str(item.get('discount', 0.0) or 0.0)) for item in self.data)
        total_tax = sum(Decimal(str(item.get('tax_levy', 0.0) or 0.0)) for item in self.data)
        total_net = sum(Decimal(str(item.get('gross_total', 0.0) or 0.0)) for item in self.data)

        writer.writerow(['', 'TOTALS', '', '', '', f"{total_gross:.2f}", f"{total_discount:.2f}", f"{total_tax:.2f}", f"{total_net:.2f}", ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()
        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'sales_report_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_sales_detail_csv(self, details):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Sales Detail for {details.get('number')}"]
        writer.writerow(info_row)
        generated_info = [f"Posted by: {details.get('by')} on {details.get('issueDate')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        info_data = [
            ['Customer:', details['customer'] if details['customer'].strip() else details['customer_info']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        for label, value in info_data:
            writer.writerow([label, value])
        writer.writerow([])

        headers = ['Item Code', 'Brand', 'Item Name', 'Quantity', 'Unit Price', 'Total Price']
        writer.writerow(headers)

        total_price = Decimal('0.0')
        for item in self.data:
            qty = item.get('qty', 0) or 0
            price = Decimal(str(item.get('price', 0.0) or 0.0))
            row_total = Decimal(qty) * price
            total_price += row_total

            writer.writerow([
                item.get('code', ''),
                item.get('brand', ''),
                item.get('item', ''),
                int(qty),
                f"{price:.2f}",
                f"{row_total:.2f}",
            ])

        writer.writerow(['', '', 'TOTALS', '', '', f"{total_price:.2f}"])

        gross_amount = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        writer.writerow([])
        writer.writerow(['Gross Total :', f"{gross_amount:.2f}"])
        writer.writerow([f"Discount - {discount}% :", f"{-discount_amount:.2f}"])

        for levy in tax_levy_list:
            writer.writerow([f"{levy['name']} :", f"{levy['amount']:.2f}"])

        writer.writerow(['Net Total :', f"{net_amount:.2f}"])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()
        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'sales_detail_{details.get('number')}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_purchase_main_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Purchase Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Purchase ID', 'Date', 'Description', 'Supplier', 'Location', 'Total Amount', 'Status']
        writer.writerow(headers)

        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('supplier__name', ''),
                item.get('location_address__location_name', ''),
                f"{item.get('gross_total', 0.0):.2f}",
                item.get('status', ''),
            ])

        total_amount = sum(Decimal(str(item.get('gross_total', 0.0) or 0.0)) for item in self.data)
        writer.writerow(['', 'TOTALS', '', '', '', f"{total_amount:.2f}", ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'purchase_report_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_purchase_detail_csv(self, details):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Purchase Detail for {details.get('number')}"]
        writer.writerow(info_row)
        generated_info = [f"Posted by: {details.get('by')} on {details.get('issueDate')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        info_data = [
            ['Supplier:', details['supplier']],
            ['Location:', details['loc']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        for label, value in info_data:
            writer.writerow([label, value])
        writer.writerow([])

        headers = ['Item Code', 'Item Name', 'Brand', 'Quantity', 'Unit Price', 'Total Price']
        writer.writerow(headers)

        total_price = Decimal('0.0')
        for item in self.data:
            qty = item.get('qty', 0) or 0
            price = Decimal(str(item.get('price', 0.0) or 0.0))
            row_total = Decimal(qty) * price
            total_price += row_total

            writer.writerow([
                item.get('code', ''),
                item.get('item', ''),
                item.get('brand', ''),
                int(qty),
                f"{price:.2f}",
                f"{row_total:.2f}",
            ])

        writer.writerow(['', '', 'TOTALS', '', '', f"{total_price:.2f}"])

        gross_amount = sum(Decimal(str((item.get('qty', 0.0) * item.get('price', 0.0)) or 0.0)) for item in self.data)
        discount = details.get('discount', 0.0)
        discount_amount = gross_amount * Decimal(str(discount)) / Decimal('100.0')
        after_discount = gross_amount - discount_amount
        tax_levy = json.loads(details.get('tax_levy', [])[0]) if details.get('tax_levy') else []

        tax_levy_list = []
        net_amount = after_discount
        for levy in tax_levy:

            rate = Decimal(str(levy.get('rate', 0.0)))
            name = levy.get('label', '')
            tax_amount = after_discount * rate / Decimal('100.0')
            net_amount += tax_amount

            tax_levy_list.append({'name': name, 'rate': rate, 'amount': tax_amount})

        writer.writerow([])
        writer.writerow(['Gross Total :', f"{gross_amount:.2f}"])
        writer.writerow([f"Discount - {discount}% :", f"{-discount_amount:.2f}"])

        for levy in tax_levy_list:
            writer.writerow([f"{levy['name']} :", f"{levy['amount']:.2f}"])

        writer.writerow(['Net Total :', f"{net_amount:.2f}"])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()
        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'purchase_detail_{details.get('number')}_{today}.csv',
            'type': 'text/csv'
        }
        