from react_work import models
from reportlab.platypus import SimpleDocTemplate, Table as RLTable, TableStyle, Paragraph, Spacer
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table as XLTable, TableStyleInfo
from io import BytesIO, StringIO
import base64
import csv
from datetime import datetime
from decimal import Decimal


class PDF():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Inventory Items Report for {self.location}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Item Name', 'Brand', 'Quantity', 'Cost', 'Price', 'Total Value']
        table_data = [headers]

        total_quantity = 0
        total_value = Decimal('0.0')

        for item in self.data:
            qty = item.get('quantity', 0) or 0
            cost = Decimal(str(item.get('purchase_price', 0.0) or 0.0))
            price = item.get('sales_price', 0.0) or 0.0
            row_total = Decimal(qty) * cost

            total_quantity += qty
            total_value += row_total

            row = [
                item.get('code', ''),
                item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''),
                item.get('brand__name', ''),
                str(int(qty)),
                f"{cost:.2f}",
                f"{price:.2f}",
                f"{row_total:.2f}",
            ]
            table_data.append(row)

        totals_row = [
            '',
            'TOTALS',
            '',
            str(total_quantity),
            '',
            '',
            f"{total_value:.2f}",
        ]
        table_data.append(totals_row)

        col_widths = [60, 170, 100, 50, 60, 60, 70]

        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),

            ('FONTNAME', (1, -1), (1, -1), 'Helvetica-Bold'),
            ('TEXTCOLOR', (1, -1), (1, -1), colors.black),
            ('SPAN', (0, -1), (0, -1)),
        ])
        rl_table.setStyle(rl_style)

        flowables.append(rl_table)
        doc.build(flowables)

        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_transfer_main_pdf(self):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))
        
        headers = ['Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']

        table_data = [headers]
        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('from_loc__location_name', ''),
                item.get('to_loc__location_name', ''),
                str(int(item.get('total_quantity', 0) or 0)),
                item.get('status', ''),
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('total_quantity', 0) or 0) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            str(total_quantity),
            '',
        ]
        table_data.append(totals_row)

        col_widths = [82, 68, 150, 90, 90, 50, 70]
        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (2, 1), (2, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])
        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.pdf',
            'type': 'application/pdf'
        }
    
    def generate_transfer_detail_pdf(self, details):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, leftMargin=40, rightMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        flowables = []

        title = Paragraph(f"Transfer Detail for {details.get('number')}", styles['Heading2'])
        flowables.append(title)
        flowables.append(Spacer(1, 12))

        generated_info = Paragraph(f"Posted by: {details.get('by')} on {details.get('issueDate')}", styles['Normal'])
        flowables.append(generated_info)
        flowables.append(Spacer(1, 12))

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        info_table = RLTable(info_data, colWidths=[80, 400])
        info_style = TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ])
        info_table.setStyle(info_style)
        flowables.append(info_table)
        flowables.append(Spacer(1, 12))

        headers = ['Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        table_data = [headers]

        for item in self.data:
            row = [
                item.get('code', ''),
                item.get('name', ''),
                item.get('brand', ''),
                item.get('category', ''),
                item.get('model', ''),
                str(int(item.get('qty', 0) or 0)),
                item.get('unit', ''),
            ]
            table_data.append(row)

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        totals_row = [
            '',
            'TOTALS',
            '',
            '',
            '',
            str(total_quantity),
            '',
        ]
        table_data.append(totals_row)

        col_widths = [70, 150, 100, 100, 80, 50, 50]

        rl_table = RLTable(table_data, colWidths=col_widths, repeatRows=1)
        rl_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#CCCCCC')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (1, 1), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ])
        rl_table.setStyle(rl_style)
        flowables.append(rl_table)

        doc.build(flowables)
        buffer.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(buffer.getvalue()).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.pdf',
            'type': 'application/pdf'
        }



class XLSX():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Inventory Items")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Inventory Items Report for {self.location}"
        ws.merge_cells('A1:K1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:K2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Item Code', 'Item Name', 'Category', 'Brand', 'Model', 'Quantity', 'Unit', 'Cost', 'Price', 'Total Value']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        total_quantity = 0
        total_value = Decimal('0.0')

        for row_index, item in enumerate(self.data, start=5):
            qty = int(item.get('quantity', 0) or 0)
            cost_raw = item.get('purchase_price', 0.0) or 0.0

            cost = Decimal(str(cost_raw))
            row_total = Decimal(qty) * cost

            total_quantity += int(qty)
            total_value += row_total

            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''))
            ws.cell(row=row_index, column=4, value=item.get('category__name', ''))
            ws.cell(row=row_index, column=5, value=item.get('brand__name', ''))
            ws.cell(row=row_index, column=6, value=item.get('model', ''))
            ws.cell(row=row_index, column=7, value=int(qty))
            ws.cell(row=row_index, column=8, value=item.get('unit__suffix', ''))

            ws.cell(row=row_index, column=9, value=float(cost))
            ws.cell(row=row_index, column=10, value=float(item.get('sales_price', 0.0)))
            ws.cell(row=row_index, column=11, value=float(row_total))

        last_data_row = 4 + len(self.data)
        totals_row = last_data_row + 1
        ws.cell(row=totals_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=totals_row, column=7, value=total_quantity).font = Font(bold=True)
        ws.cell(row=totals_row, column=11, value=total_value).font = Font(bold=True)

        last_row = max(4, last_data_row + 1)
        ref = f"B4:K{last_row}"
        table = XLTable(displayName="ItemsTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)

        ws.sheet_view.showGridLines = False

        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_transfer_main_xlsx(self):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Transfer Report")
        ws.freeze_panes = 'A5'

        header_font = Font(bold=True)

        ws['A1'] = f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"
        ws.merge_cells('A1:H1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ws.merge_cells('A2:H2')
        ws['A2'].alignment = Alignment(horizontal='center')

        headers = ['', 'Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=4, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=5):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '')
            ws.cell(row=row_index, column=4, value=item.get('description', ''))
            ws.cell(row=row_index, column=5, value=item.get('from_loc__location_name', ''))
            ws.cell(row=row_index, column=6, value=item.get('to_loc__location_name', ''))
            ws.cell(row=row_index, column=7, value=int(item.get('total_quantity', 0) or 0))
            ws.cell(row=row_index, column=8, value=item.get('status', ''))

        last_row = 4 + len(self.data)

        total_row = last_row + 1
        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G5:G{last_row})").font = Font(bold=True)
        

        last_row = max(4, last_row + 1)
        ref = f"B4:H{last_row}"
        table = XLTable(displayName="TransferTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)

        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }
    
    def generate_transfer_detail_xlsx(self, details):
        wb = Workbook()

        active_sheet = wb.active
        if active_sheet is not None:
            wb.remove(active_sheet)
        ws = wb.create_sheet(title="Transfer Detail")
        ws.freeze_panes = 'A10'

        header_font = Font(bold=True)

        ws['A1'] = f"Transfer Detail for {details.get('number')}"
        ws.merge_cells('A1:G1')
        ws['A1'].font = Font(bold=True, size=14)
        ws['A1'].alignment = Alignment(horizontal='center')

        ws['A2'] = f"Posted by: {details.get('by')} on {details.get('issueDate')}"
        ws.merge_cells('A2:G2')
        ws['A2'].alignment = Alignment(horizontal='center')

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']]
        ]
        for row_offset, (label, value) in enumerate(info_data, start=4):
            ws.cell(row=row_offset, column=2, value=label).font = Font(bold=True)
            ws.cell(row=row_offset, column=3, value=value)

        headers = ['', 'Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        for col, header in enumerate(headers, start=1):
            cell = ws.cell(row=9, column=col)
            cell.value = header
            cell.font = header_font
            cell.alignment = Alignment(horizontal='center')

        for row_index, item in enumerate(self.data, start=10):
            ws.cell(row=row_index, column=2, value=item.get('code', ''))
            ws.cell(row=row_index, column=3, value=item.get('name', ''))
            ws.cell(row=row_index, column=4, value=item.get('brand', ''))
            ws.cell(row=row_index, column=5, value=item.get('category', ''))
            ws.cell(row=row_index, column=6, value=item.get('model', ''))
            ws.cell(row=row_index, column=7, value=int(item.get('qty', 0) or 0))
            ws.cell(row=row_index, column=8, value=item.get('unit', ''))

        last_row = 9 + len(self.data)
        total_row = last_row + 1
        ws.cell(row=total_row, column=4, value="TOTALS").font = Font(bold=True)
        ws.cell(row=total_row, column=7, value=f"=SUM(G7:G{last_row})").font = Font(bold=True)

        last_row = max(8, last_row + 1)
        ref = f"B9:H{last_row}"
        table = XLTable(displayName="TransferDetailTable", ref=ref)
        style = TableStyleInfo(name="TableStyleMedium2", showFirstColumn=False,
                               showLastColumn=False, showRowStripes=True, showColumnStripes=False)
        table.tableStyleInfo = style
        ws.add_table(table)
        ws.sheet_view.showGridLines = False
        for idx in range(2, ws.max_column + 1):
            column_letter = get_column_letter(idx)
            max_length = 0
            for cell in ws[column_letter]:
                if cell.value is not None:
                    max_length = max(max_length, len(str(cell.value)))
            ws.column_dimensions[column_letter].width = max_length + 2

        excel_file = BytesIO()
        wb.save(excel_file)
        excel_file.seek(0)
        today = datetime.now()

        return {
            'file': base64.b64encode(excel_file.getvalue()).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.xlsx',
            'type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        }


class CSV():
    def __init__(self, data, location, start, end, user):
        self.data = data
        self.location = location
        self.start = start
        self.end = end
        self.user = user

    def generate_item_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Inventory Items Report for {self.location}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Item Code', 'Item Name', 'Category', 'Brand', 'Model', 'Quantity', 'Unit', 'Cost', 'Price', 'Total Value']
        writer.writerow(headers)

        total_quantity = 0
        total_value = Decimal('0.0')

        for item in self.data:
            qty = item.get('quantity', 0) or 0
            cost = Decimal(str(item.get('purchase_price', 0.0) or 0.0))
            row_total = Decimal(qty) * cost

            total_quantity += int(qty)
            total_value += row_total

            writer.writerow([
                item.get('code', ''),
                item.get('item_name', '') if isinstance(item.get('item_name', ''), str) else item.get('item_name_1', ''),
                item.get('category__name', ''),
                item.get('brand__name', ''),
                item.get('model', ''),
                int(qty),
                item.get('unit__suffix', ''),
                f"{cost:.2f}",
                f"{item.get('sales_price', 0.0):.2f}",
                f"{row_total:.2f}",
            ])

        writer.writerow(['', 'TOTALS', '', '', '', total_quantity, '', '', '', f"{total_value:.2f}"])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'inventory_items_{self.location}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_transfer_main_csv(self):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Transfer Report for {self.user.per_location_access if self.user.admin is False else "All Locations"}"]
        writer.writerow(info_row)
        generated_info = [f"Generated by: {self.user.user_name} on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        headers = ['Transfer ID', 'Date', 'Description', 'Source', 'Destination','Quantity', 'Status']
        writer.writerow(headers)

        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('date', '').strftime('%Y-%m-%d') if item.get('date', '') else '',
                item.get('description', ''),
                item.get('from_loc__location_name', ''),
                item.get('to_loc__location_name', ''),
                int(item.get('total_quantity', 0) or 0),
                item.get('status', ''),
            ])

        writer.writerow(['', 'TOTALS', '', '', '', f"=SUM(F5:F{len(self.data)+1})", ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()

        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'transfer_report_{self.location}_{today}.csv',
            'type': 'text/csv'
        }
    
    def generate_transfer_detail_csv(self, details):
        buffer = StringIO()

        writer = csv.writer(buffer)

        info_row = [f"Transfer Detail for {details.get('number')}"]
        writer.writerow(info_row)
        generated_info = [f"Posted by: {details.get('by')} on {details.get('issueDate')}"]
        writer.writerow(generated_info)
        writer.writerow([])

        info_data = [
            ['Source:', details['from']],
            ['Destination:', details['to']],
            ['Date:', details['issueDate'].strftime('%Y-%m-%d') if details['issueDate'] else ''],
            ['Description:', details['description']],
            ['Status:', details['status']],
        ]
        for label, value in info_data:
            writer.writerow([label, value])
        writer.writerow([])

        headers = ['Item Code', 'Item Name', 'Brand', 'Category', 'Model', 'Quantity', 'Unit']
        writer.writerow(headers)

        for item in self.data:
            writer.writerow([
                item.get('code', ''),
                item.get('name', ''),
                item.get('brand', ''),
                item.get('category', ''),
                item.get('model', ''),
                int(item.get('qty', 0) or 0),
                item.get('unit', ''),
            ])

        total_quantity = sum(int(item.get('qty', 0) or 0) for item in self.data)
        writer.writerow(['', 'TOTALS', '', '', '', total_quantity, ''])

        csv_bytes = buffer.getvalue().encode('utf-8')
        buffer.close()
        today = datetime.now()

        return {
            'file': base64.b64encode(csv_bytes).decode('utf-8'),
            'filename': f'transfer_detail_{details.get('number')}_{today}.csv',
            'type': 'text/csv'
        }