# Generated by Django 5.2.6 on 2025-10-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_summary', models.BooleanField(default=False)),
                ('stock_movement', models.BooleanField(default=False)),
                ('stock_ageing', models.BooleanField(default=False)),
                ('inventory_valuation', models.BooleanField(default=False)),
                ('sales_records', models.BooleanField(default=False)),
                ('sales_profit', models.BooleanField(default=False)),
                ('purchase_records', models.BooleanField(default=False)),
                ('cash_flow', models.BooleanField(default=False)),
                ('sales_performance', models.BooleanField(default=False)),
                ('customer_insights', models.BooleanField(default=False)),
                ('supplier_insights', models.BooleanField(default=False)),
                ('profit_and_loss', models.BooleanField(default=False)),
                ('trial_balance', models.BooleanField(default=False)),
                ('purchase_metrics', models.BooleanField(default=False)),
                ('aged_payables', models.BooleanField(default=False)),
                ('aged_receivables', models.BooleanField(default=False)),
                ('bussiness_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.bussiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='react_work.current_user')),
            ],
            options={
                'indexes': [models.Index(fields=['bussiness_name'], name='react_work__bussine_f6bdb1_idx'), models.Index(fields=['user'], name='react_work__user_id_f3bba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='setting_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_settings', models.BooleanField(default=False)),
                ('category_settings', models.BooleanField(default=False)),
                ('unit_settings', models.BooleanField(default=False)),
                ('brand_settings', models.BooleanField(default=False)),
                ('tax_levy_settings', models.BooleanField(default=False)),
                ('currency_settings', models.BooleanField(default=False)),
                ('user_management_settings', models.BooleanField(default=False)),
                ('user_permissions_settings', models.BooleanField(default=False)),
                ('bussiness_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.bussiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='react_work.current_user')),
            ],
            options={
                'indexes': [models.Index(fields=['bussiness_name'], name='react_work__bussine_5e6f1b_idx'), models.Index(fields=['user'], name='react_work__user_id_2bab55_idx')],
            },
        ),
    ]
