# Generated by Django 4.2.11 on 2025-08-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_balance',
            name='quantity_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item_balance',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item_balance',
            name='value_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='item_balance',
            name='value_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
