# Generated by Django 5.2.6 on 2025-10-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_balance',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.bussiness'),
        ),
        migrations.AlterField(
            model_name='customer_balance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.customer'),
        ),
        migrations.AlterField(
            model_name='customer_balance',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.month_period'),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='react_work.inventory_category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='react_work.inventory_location'),
        ),
        migrations.AlterField(
            model_name='supplier_balance',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.bussiness'),
        ),
        migrations.AlterField(
            model_name='supplier_balance',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.month_period'),
        ),
        migrations.AlterField(
            model_name='supplier_balance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_work.supplier'),
        ),
    ]
