# Generated by Django 5.2.6 on 2025-10-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_work', '0002_report_permissions_setting_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_permissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report_user', to='react_work.current_user'),
        ),
        migrations.AlterField(
            model_name='setting_permissions',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='setting_user', to='react_work.current_user'),
        ),
    ]
