# Generated by Django 5.2.6 on 2025-12-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_work', '0003_alter_report_permissions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_user',
            name='date_access',
            field=models.BooleanField(default=False),
        ),
    ]
